"""add floating notes

Revision ID: 103e6b03e284
Revises: 9826ee34bd8a
Create Date: 2026-03-03 13:08:49.763428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103e6b03e284'
down_revision = '9826ee34bd8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('floating_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flock_id', sa.Integer(), nullable=False),
    sa.Column('chart_id', sa.String(length=50), nullable=False),
    sa.Column('x_value', sa.String(length=50), nullable=False),
    sa.Column('y_value', sa.Float(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flock_id'], ['flock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('floating_note')
    # ### end Alembic commands ###
