"""Add Global Hatching Egg Pct

Revision ID: 1a2b3c4d5e6f
Revises: 232a42d463c2, 444855f831c7
Create Date: 2026-02-25 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2b3c4d5e6f'
down_revision = ('232a42d463c2', '444855f831c7')
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_standard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('std_hatching_egg_pct', sa.Float(), nullable=True))
        # Set default value for existing rows
        batch_op.execute("UPDATE global_standard SET std_hatching_egg_pct = 96.0 WHERE std_hatching_egg_pct IS NULL")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_standard', schema=None) as batch_op:
        batch_op.drop_column('std_hatching_egg_pct')

    # ### end Alembic commands ###
