"""add system audit log

Revision ID: 227589a3a171
Revises: b191e49bc61d
Create Date: 2026-03-02 03:06:08.240480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '227589a3a171'
down_revision = 'b191e49bc61d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('performance_impact', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_audit_log')
    # ### end Alembic commands ###
