"""add_egg_weight_and_hatchability

Revision ID: 232a42d463c2
Revises: 93587f38221b
Create Date: 2026-02-19 06:22:07.666263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '232a42d463c2'
down_revision = '93587f38221b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('standard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('std_egg_weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('std_hatchability', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('standard', schema=None) as batch_op:
        batch_op.drop_column('std_hatchability')
        batch_op.drop_column('std_egg_weight')

    # ### end Alembic commands ###
