"""Remove legacy dashboard tables

Revision ID: 3aab2d252ffe
Revises: 44c2f925aa84
Create Date: 2026-03-17 05:37:19.175509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aab2d252ffe'
down_revision = '44c2f925aa84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('feed_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('global_standard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('std_mortality_daily', sa.Float(), nullable=True),
    sa.Column('std_mortality_weekly', sa.Float(), nullable=True),
    sa.Column('std_hatching_egg_pct', sa.Float(), nullable=True),
    sa.Column('login_required', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('house',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('inventory_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('current_stock', sa.Float(), nullable=True),
    sa.Column('min_stock_level', sa.Float(), nullable=True),
    sa.Column('doses_per_unit', sa.Integer(), nullable=True),
    sa.Column('batch_number', sa.String(length=50), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('cost_per_unit', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('standard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('std_mortality_male', sa.Float(), nullable=True),
    sa.Column('std_mortality_female', sa.Float(), nullable=True),
    sa.Column('std_bw_male', sa.Integer(), nullable=True),
    sa.Column('std_bw_female', sa.Integer(), nullable=True),
    sa.Column('std_egg_prod', sa.Float(), nullable=True),
    sa.Column('std_feed_male', sa.Float(), nullable=True),
    sa.Column('std_feed_female', sa.Float(), nullable=True),
    sa.Column('std_egg_weight', sa.Float(), nullable=True),
    sa.Column('std_hatchability', sa.Float(), nullable=True),
    sa.Column('std_hatching_egg_pct', sa.Float(), nullable=True),
    sa.Column('production_week', sa.Integer(), nullable=True),
    sa.Column('std_cum_eggs_hha', sa.Float(), nullable=True),
    sa.Column('std_cum_hatching_eggs_hha', sa.Float(), nullable=True),
    sa.Column('std_cum_chicks_hha', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week')
    )
    op.create_table('system_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('performance_impact', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ui_element',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('dept', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('theme', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('flock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('flock_id', sa.String(length=100), nullable=False),
    sa.Column('intake_date', sa.Date(), nullable=False),
    sa.Column('intake_male', sa.Integer(), nullable=True),
    sa.Column('intake_female', sa.Integer(), nullable=True),
    sa.Column('doa_male', sa.Integer(), nullable=True),
    sa.Column('doa_female', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=False),
    sa.Column('production_start_date', sa.Date(), nullable=True),
    sa.Column('start_of_lay_date', sa.Date(), nullable=True),
    sa.Column('prod_start_male', sa.Integer(), server_default='0', nullable=False),
    sa.Column('prod_start_female', sa.Integer(), server_default='0', nullable=False),
    sa.Column('prod_start_male_hosp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('prod_start_female_hosp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flock_id')
    )
    with op.batch_alter_table('flock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flock_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flock_house_id'), ['house_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flock_status'), ['status'], unique=False)

    op.create_table('inventory_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_activity_log_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_activity_log_user_id'), ['user_id'], unique=False)

    op.create_table('daily_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('males_at_start', sa.Integer(), nullable=True),
    sa.Column('females_at_start', sa.Integer(), nullable=True),
    sa.Column('mortality_male', sa.Integer(), server_default='0', nullable=False),
    sa.Column('mortality_female', sa.Integer(), server_default='0', nullable=False),
    sa.Column('mortality_male_hosp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('culls_male_hosp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('mortality_female_hosp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('culls_female_hosp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('culls_male', sa.Integer(), server_default='0', nullable=False),
    sa.Column('culls_female', sa.Integer(), server_default='0', nullable=False),
    sa.Column('males_moved_to_prod', sa.Integer(), server_default='0', nullable=False),
    sa.Column('males_moved_to_hosp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('females_moved_to_prod', sa.Integer(), server_default='0', nullable=False),
    sa.Column('females_moved_to_hosp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('feed_program', sa.String(length=50), nullable=True),
    sa.Column('feed_male_gp_bird', sa.Float(), server_default='0', nullable=False),
    sa.Column('feed_female_gp_bird', sa.Float(), server_default='0', nullable=False),
    sa.Column('feed_male', sa.Float(), server_default='0', nullable=False),
    sa.Column('feed_female', sa.Float(), server_default='0', nullable=False),
    sa.Column('eggs_collected', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cull_eggs_jumbo', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cull_eggs_small', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cull_eggs_abnormal', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cull_eggs_crack', sa.Integer(), server_default='0', nullable=False),
    sa.Column('egg_weight', sa.Float(), nullable=True),
    sa.Column('body_weight_male', sa.Integer(), nullable=True),
    sa.Column('body_weight_female', sa.Integer(), nullable=True),
    sa.Column('uniformity_male', sa.Float(), nullable=True),
    sa.Column('uniformity_female', sa.Float(), nullable=True),
    sa.Column('is_weighing_day', sa.Boolean(), nullable=True),
    sa.Column('bw_male_p1', sa.Integer(), nullable=True),
    sa.Column('bw_male_p2', sa.Integer(), nullable=True),
    sa.Column('unif_male_p1', sa.Float(), nullable=True),
    sa.Column('unif_male_p2', sa.Float(), nullable=True),
    sa.Column('bw_female_p1', sa.Integer(), nullable=True),
    sa.Column('bw_female_p2', sa.Integer(), nullable=True),
    sa.Column('bw_female_p3', sa.Integer(), nullable=True),
    sa.Column('bw_female_p4', sa.Integer(), nullable=True),
    sa.Column('unif_female_p1', sa.Float(), nullable=True),
    sa.Column('unif_female_p2', sa.Float(), nullable=True),
    sa.Column('unif_female_p3', sa.Float(), nullable=True),
    sa.Column('unif_female_p4', sa.Float(), nullable=True),
    sa.Column('standard_bw_male', sa.Integer(), nullable=True),
    sa.Column('standard_bw_female', sa.Integer(), nullable=True),
    sa.Column('water_reading_1', sa.Integer(), nullable=True),
    sa.Column('water_reading_2', sa.Integer(), nullable=True),
    sa.Column('water_reading_3', sa.Integer(), nullable=True),
    sa.Column('water_intake_calculated', sa.Float(), nullable=True),
    sa.Column('light_on_time', sa.String(length=10), nullable=True),
    sa.Column('light_off_time', sa.String(length=10), nullable=True),
    sa.Column('feed_cleanup_start', sa.String(length=10), nullable=True),
    sa.Column('feed_cleanup_end', sa.String(length=10), nullable=True),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('flushing', sa.Boolean(), nullable=True),
    sa.Column('selection_done', sa.Boolean(), nullable=True),
    sa.Column('spiking', sa.Boolean(), nullable=True),
    sa.Column('feed_code_male_id', sa.Integer(), nullable=True),
    sa.Column('feed_code_female_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feed_code_female_id'], ['feed_code.id'], ),
    sa.ForeignKeyConstraint(['feed_code_male_id'], ['feed_code.id'], ),
    sa.ForeignKeyConstraint(['flock_id'], ['flock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_log_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_log_flock_id'), ['flock_id'], unique=False)

    op.create_table('floating_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flock_id', sa.Integer(), nullable=False),
    sa.Column('chart_id', sa.String(length=50), nullable=False),
    sa.Column('x_value', sa.String(length=50), nullable=False),
    sa.Column('y_value', sa.Float(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flock_id'], ['flock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hatchability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flock_id', sa.Integer(), nullable=False),
    sa.Column('setting_date', sa.Date(), nullable=False),
    sa.Column('candling_date', sa.Date(), nullable=False),
    sa.Column('hatching_date', sa.Date(), nullable=False),
    sa.Column('egg_set', sa.Integer(), nullable=True),
    sa.Column('clear_eggs', sa.Integer(), nullable=True),
    sa.Column('rotten_eggs', sa.Integer(), nullable=True),
    sa.Column('hatched_chicks', sa.Integer(), nullable=True),
    sa.Column('male_ratio_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['flock_id'], ['flock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imported_weekly_benchmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flock_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('mortality_male', sa.Integer(), nullable=True),
    sa.Column('mortality_female', sa.Integer(), nullable=True),
    sa.Column('eggs_collected', sa.Integer(), nullable=True),
    sa.Column('bw_male', sa.Integer(), nullable=True),
    sa.Column('bw_female', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flock_id'], ['flock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flock_id', sa.Integer(), nullable=False),
    sa.Column('drug_name', sa.String(length=100), nullable=False),
    sa.Column('dosage', sa.String(length=50), nullable=False),
    sa.Column('amount_used', sa.String(length=100), nullable=True),
    sa.Column('amount_used_qty', sa.Float(), nullable=True),
    sa.Column('withdrawal_period_days', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('inventory_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flock_id'], ['flock.id'], ),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sampling_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flock_id', sa.Integer(), nullable=False),
    sa.Column('age_week', sa.Integer(), nullable=False),
    sa.Column('test_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('result_file', sa.String(length=200), nullable=True),
    sa.Column('upload_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['flock_id'], ['flock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vaccine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flock_id', sa.Integer(), nullable=False),
    sa.Column('age_code', sa.String(length=10), nullable=False),
    sa.Column('vaccine_name', sa.String(length=200), nullable=False),
    sa.Column('route', sa.String(length=50), nullable=True),
    sa.Column('est_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('doses_per_unit', sa.Integer(), nullable=True),
    sa.Column('inventory_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flock_id'], ['flock.id'], ),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clinical_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['daily_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partition_weight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('partition_name', sa.String(length=10), nullable=False),
    sa.Column('body_weight', sa.Integer(), nullable=True),
    sa.Column('uniformity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['daily_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_log_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=200), nullable=False),
    sa.Column('original_filename', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['daily_log.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['clinical_note.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_log_photo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_log_photo_log_id'), ['log_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_log_photo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_log_photo_log_id'))

    op.drop_table('daily_log_photo')
    op.drop_table('partition_weight')
    op.drop_table('clinical_note')
    op.drop_table('vaccine')
    op.drop_table('sampling_event')
    op.drop_table('medication')
    op.drop_table('imported_weekly_benchmark')
    op.drop_table('hatchability')
    op.drop_table('floating_note')
    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_log_flock_id'))
        batch_op.drop_index(batch_op.f('ix_daily_log_date'))

    op.drop_table('daily_log')
    with op.batch_alter_table('user_activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_activity_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_activity_log_timestamp'))

    op.drop_table('user_activity_log')
    op.drop_table('inventory_transaction')
    with op.batch_alter_table('flock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flock_status'))
        batch_op.drop_index(batch_op.f('ix_flock_house_id'))
        batch_op.drop_index(batch_op.f('ix_flock_farm_id'))

    op.drop_table('flock')
    op.drop_table('user')
    op.drop_table('ui_element')
    op.drop_table('system_audit_log')
    op.drop_table('standard')
    op.drop_table('inventory_item')
    op.drop_table('house')
    op.drop_table('global_standard')
    op.drop_table('feed_code')
    op.drop_table('farm')
    # ### end Alembic commands ###
