"""Add std_cum_hatching_eggs_hha to standard

Revision ID: 3b17d3d18d84
Revises: 542e4b248850
Create Date: 2026-02-24 07:10:37.075358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b17d3d18d84'
down_revision = '542e4b248850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('standard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('std_cum_hatching_eggs_hha', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('standard', schema=None) as batch_op:
        batch_op.drop_column('std_cum_hatching_eggs_hha')

    # ### end Alembic commands ###
