"""Add active_theme to GlobalStandard

Revision ID: 3f08ca69aca6
Revises: fe4643e18171
Create Date: 2026-03-03 00:39:01.553798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f08ca69aca6'
down_revision = 'fe4643e18171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_data')
    with op.batch_alter_table('global_standard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_theme', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_standard', schema=None) as batch_op:
        batch_op.drop_column('active_theme')

    op.create_table('weekly_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('flock_id', sa.INTEGER(), nullable=False),
    sa.Column('week', sa.INTEGER(), nullable=False),
    sa.Column('mortality_male', sa.INTEGER(), nullable=True),
    sa.Column('mortality_female', sa.INTEGER(), nullable=True),
    sa.Column('culls_male', sa.INTEGER(), nullable=True),
    sa.Column('culls_female', sa.INTEGER(), nullable=True),
    sa.Column('eggs_collected', sa.INTEGER(), nullable=True),
    sa.Column('bw_male', sa.INTEGER(), nullable=True),
    sa.Column('bw_female', sa.INTEGER(), nullable=True),
    sa.Column('feed_male', sa.FLOAT(), nullable=True),
    sa.Column('feed_female', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['flock_id'], ['flock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
