"""Enforce defaults for DailyLog

Revision ID: 444855f831c7
Revises: a7d9b437cae8
Create Date: 2026-02-14 05:39:39.231438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '444855f831c7'
down_revision = 'a7d9b437cae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### Data Backfill: Ensure no NULLs exist before setting NOT NULL ###
    op.execute("UPDATE daily_log SET mortality_male = 0 WHERE mortality_male IS NULL")
    op.execute("UPDATE daily_log SET mortality_female = 0 WHERE mortality_female IS NULL")
    op.execute("UPDATE daily_log SET mortality_male_hosp = 0 WHERE mortality_male_hosp IS NULL")
    op.execute("UPDATE daily_log SET culls_male_hosp = 0 WHERE culls_male_hosp IS NULL")
    op.execute("UPDATE daily_log SET mortality_female_hosp = 0 WHERE mortality_female_hosp IS NULL")
    op.execute("UPDATE daily_log SET culls_female_hosp = 0 WHERE culls_female_hosp IS NULL")
    op.execute("UPDATE daily_log SET culls_male = 0 WHERE culls_male IS NULL")
    op.execute("UPDATE daily_log SET culls_female = 0 WHERE culls_female IS NULL")
    op.execute("UPDATE daily_log SET males_moved_to_prod = 0 WHERE males_moved_to_prod IS NULL")
    op.execute("UPDATE daily_log SET males_moved_to_hosp = 0 WHERE males_moved_to_hosp IS NULL")
    op.execute("UPDATE daily_log SET females_moved_to_prod = 0 WHERE females_moved_to_prod IS NULL")
    op.execute("UPDATE daily_log SET females_moved_to_hosp = 0 WHERE females_moved_to_hosp IS NULL")
    op.execute("UPDATE daily_log SET feed_male_gp_bird = 0 WHERE feed_male_gp_bird IS NULL")
    op.execute("UPDATE daily_log SET feed_female_gp_bird = 0 WHERE feed_female_gp_bird IS NULL")
    op.execute("UPDATE daily_log SET feed_male = 0 WHERE feed_male IS NULL")
    op.execute("UPDATE daily_log SET feed_female = 0 WHERE feed_female IS NULL")
    op.execute("UPDATE daily_log SET eggs_collected = 0 WHERE eggs_collected IS NULL")
    op.execute("UPDATE daily_log SET cull_eggs_jumbo = 0 WHERE cull_eggs_jumbo IS NULL")
    op.execute("UPDATE daily_log SET cull_eggs_small = 0 WHERE cull_eggs_small IS NULL")
    op.execute("UPDATE daily_log SET cull_eggs_abnormal = 0 WHERE cull_eggs_abnormal IS NULL")
    op.execute("UPDATE daily_log SET cull_eggs_crack = 0 WHERE cull_eggs_crack IS NULL")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        batch_op.alter_column('mortality_male',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('mortality_female',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('mortality_male_hosp',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('culls_male_hosp',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('mortality_female_hosp',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('culls_female_hosp',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('culls_male',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('culls_female',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('males_moved_to_prod',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('males_moved_to_hosp',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('females_moved_to_prod',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('females_moved_to_hosp',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('feed_male_gp_bird',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('feed_female_gp_bird',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('feed_male',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('feed_female',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('eggs_collected',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('cull_eggs_jumbo',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('cull_eggs_small',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('cull_eggs_abnormal',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('cull_eggs_crack',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        batch_op.alter_column('cull_eggs_crack',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('cull_eggs_abnormal',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('cull_eggs_small',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('cull_eggs_jumbo',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('eggs_collected',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('feed_female',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('feed_male',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('feed_female_gp_bird',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('feed_male_gp_bird',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('females_moved_to_hosp',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('females_moved_to_prod',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('males_moved_to_hosp',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('males_moved_to_prod',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('culls_female',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('culls_male',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('culls_female_hosp',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('mortality_female_hosp',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('culls_male_hosp',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('mortality_male_hosp',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('mortality_female',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('mortality_male',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
