"""Sync inventory columns to DailyLog

Revision ID: 44c2f925aa84
Revises: a035faca5735
Create Date: 2026-03-11 05:05:46.956176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c2f925aa84'
down_revision = 'a035faca5735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('flock_id', sa.INTEGER(), nullable=False),
    sa.Column('week', sa.INTEGER(), nullable=False),
    sa.Column('mortality_male', sa.INTEGER(), nullable=True),
    sa.Column('mortality_female', sa.INTEGER(), nullable=True),
    sa.Column('culls_male', sa.INTEGER(), nullable=True),
    sa.Column('culls_female', sa.INTEGER(), nullable=True),
    sa.Column('eggs_collected', sa.INTEGER(), nullable=True),
    sa.Column('bw_male', sa.INTEGER(), nullable=True),
    sa.Column('bw_female', sa.INTEGER(), nullable=True),
    sa.Column('feed_male', sa.FLOAT(), nullable=True),
    sa.Column('feed_female', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['flock_id'], ['flock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
