"""Initial migration

Revision ID: 4ea3b6f0007c
Revises:
Create Date: 2026-02-12 02:50:31.345145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ea3b6f0007c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('house',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('inventory_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('current_stock', sa.Float(), nullable=True),
    sa.Column('min_stock_level', sa.Float(), nullable=True),
    sa.Column('doses_per_unit', sa.Integer(), nullable=True),
    sa.Column('batch_number', sa.String(length=50), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('cost_per_unit', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('standard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('std_mortality_male', sa.Float(), nullable=True),
    sa.Column('std_mortality_female', sa.Float(), nullable=True),
    sa.Column('std_bw_male', sa.Float(), nullable=True),
    sa.Column('std_bw_female', sa.Float(), nullable=True),
    sa.Column('std_egg_prod', sa.Float(), nullable=True),
    sa.Column('std_feed_male', sa.Float(), nullable=True),
    sa.Column('std_feed_female', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week')
    )
    op.create_table('chart_configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('chart_type', sa.String(length=20), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=100), nullable=False),
    sa.Column('intake_date', sa.Date(), nullable=False),
    sa.Column('intake_male', sa.Integer(), nullable=True),
    sa.Column('intake_female', sa.Integer(), nullable=True),
    sa.Column('doa_male', sa.Integer(), nullable=True),
    sa.Column('doa_female', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=False),
    sa.Column('production_start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id')
    )
    op.create_table('inventory_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('overview_configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('visible_metrics_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('house_id')
    )
    op.create_table('daily_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('mortality_male', sa.Integer(), nullable=True),
    sa.Column('mortality_female', sa.Integer(), nullable=True),
    sa.Column('mortality_male_hosp', sa.Integer(), nullable=True),
    sa.Column('culls_male_hosp', sa.Integer(), nullable=True),
    sa.Column('culls_male', sa.Integer(), nullable=True),
    sa.Column('culls_female', sa.Integer(), nullable=True),
    sa.Column('males_moved_to_prod', sa.Integer(), nullable=True),
    sa.Column('males_moved_to_hosp', sa.Integer(), nullable=True),
    sa.Column('feed_program', sa.String(length=50), nullable=True),
    sa.Column('feed_male_gp_bird', sa.Float(), nullable=True),
    sa.Column('feed_female_gp_bird', sa.Float(), nullable=True),
    sa.Column('feed_male', sa.Float(), nullable=True),
    sa.Column('feed_female', sa.Float(), nullable=True),
    sa.Column('eggs_collected', sa.Integer(), nullable=True),
    sa.Column('cull_eggs_jumbo', sa.Integer(), nullable=True),
    sa.Column('cull_eggs_small', sa.Integer(), nullable=True),
    sa.Column('cull_eggs_abnormal', sa.Integer(), nullable=True),
    sa.Column('cull_eggs_crack', sa.Integer(), nullable=True),
    sa.Column('egg_weight', sa.Float(), nullable=True),
    sa.Column('body_weight_male', sa.Float(), nullable=True),
    sa.Column('body_weight_female', sa.Float(), nullable=True),
    sa.Column('uniformity_male', sa.Float(), nullable=True),
    sa.Column('uniformity_female', sa.Float(), nullable=True),
    sa.Column('is_weighing_day', sa.Boolean(), nullable=True),
    sa.Column('bw_male_p1', sa.Float(), nullable=True),
    sa.Column('bw_male_p2', sa.Float(), nullable=True),
    sa.Column('unif_male_p1', sa.Float(), nullable=True),
    sa.Column('unif_male_p2', sa.Float(), nullable=True),
    sa.Column('bw_female_p1', sa.Float(), nullable=True),
    sa.Column('bw_female_p2', sa.Float(), nullable=True),
    sa.Column('bw_female_p3', sa.Float(), nullable=True),
    sa.Column('bw_female_p4', sa.Float(), nullable=True),
    sa.Column('unif_female_p1', sa.Float(), nullable=True),
    sa.Column('unif_female_p2', sa.Float(), nullable=True),
    sa.Column('unif_female_p3', sa.Float(), nullable=True),
    sa.Column('unif_female_p4', sa.Float(), nullable=True),
    sa.Column('standard_bw_male', sa.Float(), nullable=True),
    sa.Column('standard_bw_female', sa.Float(), nullable=True),
    sa.Column('water_reading_1', sa.Integer(), nullable=True),
    sa.Column('water_reading_2', sa.Integer(), nullable=True),
    sa.Column('water_reading_3', sa.Integer(), nullable=True),
    sa.Column('water_intake_calculated', sa.Float(), nullable=True),
    sa.Column('light_on_time', sa.String(length=10), nullable=True),
    sa.Column('light_off_time', sa.String(length=10), nullable=True),
    sa.Column('feed_cleanup_start', sa.String(length=10), nullable=True),
    sa.Column('feed_cleanup_end', sa.String(length=10), nullable=True),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('photo_path', sa.String(length=200), nullable=True),
    sa.Column('flushing', sa.Boolean(), nullable=True),
    sa.Column('feed_code_male_id', sa.Integer(), nullable=True),
    sa.Column('feed_code_female_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feed_code_female_id'], ['feed_code.id'], ),
    sa.ForeignKeyConstraint(['feed_code_male_id'], ['feed_code.id'], ),
    sa.ForeignKeyConstraint(['flock_id'], ['flock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hatchability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flock_id', sa.Integer(), nullable=False),
    sa.Column('setting_date', sa.Date(), nullable=False),
    sa.Column('candling_date', sa.Date(), nullable=False),
    sa.Column('hatching_date', sa.Date(), nullable=False),
    sa.Column('egg_set', sa.Integer(), nullable=True),
    sa.Column('clear_eggs', sa.Integer(), nullable=True),
    sa.Column('rotten_eggs', sa.Integer(), nullable=True),
    sa.Column('hatched_chicks', sa.Integer(), nullable=True),
    sa.Column('male_ratio_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['flock_id'], ['flock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imported_weekly_benchmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flock_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('mortality_male', sa.Integer(), nullable=True),
    sa.Column('mortality_female', sa.Integer(), nullable=True),
    sa.Column('eggs_collected', sa.Integer(), nullable=True),
    sa.Column('bw_male', sa.Float(), nullable=True),
    sa.Column('bw_female', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['flock_id'], ['flock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flock_id', sa.Integer(), nullable=False),
    sa.Column('drug_name', sa.String(length=100), nullable=False),
    sa.Column('dosage', sa.String(length=50), nullable=False),
    sa.Column('amount_used', sa.String(length=100), nullable=True),
    sa.Column('amount_used_qty', sa.Float(), nullable=True),
    sa.Column('withdrawal_period_days', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('inventory_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flock_id'], ['flock.id'], ),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sampling_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flock_id', sa.Integer(), nullable=False),
    sa.Column('age_week', sa.Integer(), nullable=False),
    sa.Column('test_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('result_file', sa.String(length=200), nullable=True),
    sa.Column('upload_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['flock_id'], ['flock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vaccine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flock_id', sa.Integer(), nullable=False),
    sa.Column('age_code', sa.String(length=10), nullable=False),
    sa.Column('vaccine_name', sa.String(length=200), nullable=False),
    sa.Column('route', sa.String(length=50), nullable=True),
    sa.Column('est_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('doses_per_unit', sa.Integer(), nullable=True),
    sa.Column('inventory_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flock_id'], ['flock.id'], ),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flock_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('mortality_male', sa.Integer(), nullable=True),
    sa.Column('mortality_female', sa.Integer(), nullable=True),
    sa.Column('culls_male', sa.Integer(), nullable=True),
    sa.Column('culls_female', sa.Integer(), nullable=True),
    sa.Column('eggs_collected', sa.Integer(), nullable=True),
    sa.Column('bw_male', sa.Float(), nullable=True),
    sa.Column('bw_female', sa.Float(), nullable=True),
    sa.Column('feed_male', sa.Float(), nullable=True),
    sa.Column('feed_female', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['flock_id'], ['flock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partition_weight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('partition_name', sa.String(length=10), nullable=False),
    sa.Column('body_weight', sa.Float(), nullable=True),
    sa.Column('uniformity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['daily_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partition_weight')
    op.drop_table('weekly_data')
    op.drop_table('vaccine')
    op.drop_table('sampling_event')
    op.drop_table('medication')
    op.drop_table('imported_weekly_benchmark')
    op.drop_table('hatchability')
    op.drop_table('daily_log')
    op.drop_table('overview_configuration')
    op.drop_table('inventory_transaction')
    op.drop_table('flock')
    op.drop_table('chart_configuration')
    op.drop_table('standard')
    op.drop_table('inventory_item')
    op.drop_table('house')
    op.drop_table('feed_code')
    # ### end Alembic commands ###
