"""Add cumulative hha columns to standard

Revision ID: 542e4b248850
Revises: b7d8c9a0e1f2
Create Date: 2026-02-24 05:01:18.850072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '542e4b248850'
down_revision = 'b7d8c9a0e1f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('standard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('std_cum_eggs_hha', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('std_cum_chicks_hha', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('standard', schema=None) as batch_op:
        batch_op.drop_column('std_cum_chicks_hha')
        batch_op.drop_column('std_cum_eggs_hha')

    # ### end Alembic commands ###
