"""add daily_log_photo table

Revision ID: 842943bd20a2
Revises: 8a4cfaa00668
Create Date: 2026-02-25 05:39:34.316088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '842943bd20a2'
down_revision = '8a4cfaa00668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_log_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=200), nullable=False),
    sa.Column('original_filename', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['daily_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_log_photo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_log_photo_log_id'), ['log_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_log_photo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_log_photo_log_id'))

    op.drop_table('daily_log_photo')
    # ### end Alembic commands ###
