"""Add std_hatching_egg_pct to standard

Revision ID: 8a4cfaa00668
Revises: 3b17d3d18d84
Create Date: 2026-02-25 01:27:58.598050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a4cfaa00668'
down_revision = '3b17d3d18d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('standard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('std_hatching_egg_pct', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('standard', schema=None) as batch_op:
        batch_op.drop_column('std_hatching_egg_pct')

    # ### end Alembic commands ###
