"""Add production_week to Standard and start_of_lay_date to Flock

Revision ID: 8a7e82bc5eeb
Revises: 1a2b3c4d5e6f
Create Date: 2026-02-23 12:53:37.789603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a7e82bc5eeb'
down_revision = '1a2b3c4d5e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_of_lay_date', sa.Date(), nullable=True))

    with op.batch_alter_table('standard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('production_week', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('standard', schema=None) as batch_op:
        batch_op.drop_column('production_week')

    with op.batch_alter_table('flock', schema=None) as batch_op:
        batch_op.drop_column('start_of_lay_date')

    # ### end Alembic commands ###
