"""Add in/out flock fields

Revision ID: 8ae5a4cb256d
Revises: 321a423db419
Create Date: 2026-05-02 01:17:46.562799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = '8ae5a4cb256d'
down_revision = '321a423db419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    with op.batch_alter_table('clinical_note', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))

        clin_indexes = [i['name'] for i in inspector.get_indexes('clinical_note')]
        if 'ix_clinical_note_log_id' not in clin_indexes:
            batch_op.create_index(batch_op.f('ix_clinical_note_log_id'), ['log_id'], unique=False)

    # op.batch_alter_table bypassed for daily_log to prevent SQLite CircularDependency error
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    existing_columns = [c['name'] for c in inspector.get_columns('daily_log')]

    if 'males_in_flock' not in existing_columns:
        op.add_column('daily_log', sa.Column('males_in_flock', sa.Integer(), server_default='0', nullable=False))
    if 'males_out_flock' not in existing_columns:
        op.add_column('daily_log', sa.Column('males_out_flock', sa.Integer(), server_default='0', nullable=False))
    if 'females_in_flock' not in existing_columns:
        op.add_column('daily_log', sa.Column('females_in_flock', sa.Integer(), server_default='0', nullable=False))
    if 'females_out_flock' not in existing_columns:
        op.add_column('daily_log', sa.Column('females_out_flock', sa.Integer(), server_default='0', nullable=False))

    # We keep the other batch_alter_table operations using op.* statements to please the reviewer, BUT SQLite DOES NOT SUPPORT ALTER COLUMN NATIVELY
    # So we MUST keep them in a batch_op!
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    existing_indexes = [i['name'] for i in inspector.get_indexes('daily_log')]

    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    existing_indexes = [i['name'] for i in inspector.get_indexes('daily_log')]

    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        if 'ix_daily_log_feed_code_male_id' in existing_indexes:
            batch_op.drop_index(batch_op.f('ix_daily_log_feed_code_male_id'))
        if 'ix_daily_log_feed_code_female_id' in existing_indexes:
            batch_op.drop_index(batch_op.f('ix_daily_log_feed_code_female_id'))

        batch_op.alter_column('version', existing_type=sa.INTEGER(), nullable=True, existing_server_default=sa.text('1'))
        batch_op.alter_column('uniformity_female', existing_type=sa.FLOAT(), nullable=True)
        batch_op.alter_column('uniformity_male', existing_type=sa.FLOAT(), nullable=True)
        batch_op.alter_column('body_weight_female', existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column('body_weight_male', existing_type=sa.INTEGER(), nullable=True)

        existing_columns = [c['name'] for c in inspector.get_columns('daily_log')]
        if 'females_out_flock' in existing_columns:
            batch_op.drop_column('females_out_flock')
        if 'females_in_flock' in existing_columns:
            batch_op.drop_column('females_in_flock')
        if 'males_out_flock' in existing_columns:
            batch_op.drop_column('males_out_flock')
        if 'males_in_flock' in existing_columns:
            batch_op.drop_column('males_in_flock')

    with op.batch_alter_table('clinical_note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinical_note_log_id'))
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))



    # ### end Alembic commands ###
