"""Add in/out flock fields

Revision ID: 8ae5a4cb256d
Revises: 321a423db419
Create Date: 2026-05-02 01:17:46.562799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ae5a4cb256d'
down_revision = '321a423db419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_broiler_daily_log')
    with op.batch_alter_table('broiler_daily_log', schema=None) as batch_op:
        batch_op.drop_column('version')

    with op.batch_alter_table('broiler_flock', schema=None) as batch_op:
        batch_op.drop_column('version')

    with op.batch_alter_table('clinical_note', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.create_index(batch_op.f('ix_clinical_note_log_id'), ['log_id'], unique=False)

    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('males_in_flock', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('males_out_flock', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('females_in_flock', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('females_out_flock', sa.Integer(), server_default='0', nullable=False))
        batch_op.alter_column('body_weight_male',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('body_weight_female',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('uniformity_male',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('uniformity_female',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.create_index(batch_op.f('ix_daily_log_feed_code_female_id'), ['feed_code_female_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_log_feed_code_male_id'), ['feed_code_male_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('feed_male')
        batch_op.drop_column('feed_female')
        batch_op.drop_column('feed_code_id')

    with op.batch_alter_table('daily_log_photo', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.create_index(batch_op.f('ix_daily_log_photo_note_id'), ['note_id'], unique=False)

    with op.batch_alter_table('farm', schema=None) as batch_op:
        batch_op.drop_column('version')

    with op.batch_alter_table('feed_code', schema=None) as batch_op:
        batch_op.drop_column('version')

    with op.batch_alter_table('floating_note', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('flock_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('chart_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('x_value',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('y_value',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.create_index(batch_op.f('ix_floating_note_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_floating_note_flock_id'), ['flock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_floating_note_x_value'), ['x_value'], unique=False)
        batch_op.create_foreign_key(None, 'flock', ['flock_id'], ['id'])

    with op.batch_alter_table('flock', schema=None) as batch_op:
        batch_op.alter_column('farm_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('version')
        batch_op.drop_column('production_start_date')

    with op.batch_alter_table('flock_grading', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.create_index(batch_op.f('ix_flock_grading_age_week'), ['age_week'], unique=False)

    with op.batch_alter_table('global_standard', schema=None) as batch_op:
        batch_op.drop_column('version')
        batch_op.drop_column('active_theme')

    with op.batch_alter_table('hatchability', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.create_index(batch_op.f('ix_hatchability_candling_date'), ['candling_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_hatchability_flock_id'), ['flock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hatchability_hatching_date'), ['hatching_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_hatchability_setting_date'), ['setting_date'], unique=False)

    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.drop_column('version')

    with op.batch_alter_table('imported_weekly_benchmark', schema=None) as batch_op:
        batch_op.drop_column('version')

    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('inventory_transaction', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.create_index(batch_op.f('ix_inventory_transaction_inventory_item_id'), ['inventory_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transaction_transaction_date'), ['transaction_date'], unique=False)

    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.alter_column('amount_used_qty',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.create_index(batch_op.f('ix_medication_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_flock_id'), ['flock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_inventory_item_id'), ['inventory_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_start_date'), ['start_date'], unique=False)

    with op.batch_alter_table('notification_history', schema=None) as batch_op:
        batch_op.drop_column('version')

    with op.batch_alter_table('notification_rule', schema=None) as batch_op:
        batch_op.drop_column('version')

    with op.batch_alter_table('partition_weight', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.create_index(batch_op.f('ix_partition_weight_log_id'), ['log_id'], unique=False)

    with op.batch_alter_table('push_subscription', schema=None) as batch_op:
        batch_op.drop_column('version')

    with op.batch_alter_table('sampling_event', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.create_index(batch_op.f('ix_sampling_event_age_week'), ['age_week'], unique=False)
        batch_op.create_index(batch_op.f('ix_sampling_event_flock_id'), ['flock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sampling_event_status'), ['status'], unique=False)

    with op.batch_alter_table('standard', schema=None) as batch_op:
        batch_op.drop_column('version')

    with op.batch_alter_table('system_audit_log', schema=None) as batch_op:
        batch_op.drop_column('version')

    with op.batch_alter_table('ui_element', schema=None) as batch_op:
        batch_op.drop_column('version')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('version')

    with op.batch_alter_table('user_activity_log', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('resource_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('resource_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_user_activity_log_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_activity_log_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('version')

    with op.batch_alter_table('vaccine', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.create_index(batch_op.f('ix_vaccine_actual_date'), ['actual_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_vaccine_est_date'), ['est_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_vaccine_flock_id'), ['flock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vaccine_inventory_item_id'), ['inventory_item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaccine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vaccine_inventory_item_id'))
        batch_op.drop_index(batch_op.f('ix_vaccine_flock_id'))
        batch_op.drop_index(batch_op.f('ix_vaccine_est_date'))
        batch_op.drop_index(batch_op.f('ix_vaccine_actual_date'))
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('user_activity_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_activity_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_activity_log_timestamp'))
        batch_op.alter_column('resource_id',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('resource_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('ui_element', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), nullable=True))

    with op.batch_alter_table('system_audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), nullable=True))

    with op.batch_alter_table('standard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), nullable=True))

    with op.batch_alter_table('sampling_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sampling_event_status'))
        batch_op.drop_index(batch_op.f('ix_sampling_event_flock_id'))
        batch_op.drop_index(batch_op.f('ix_sampling_event_age_week'))
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('push_subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), nullable=True))

    with op.batch_alter_table('partition_weight', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partition_weight_log_id'))
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('notification_rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), nullable=True))

    with op.batch_alter_table('notification_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), nullable=True))

    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medication_start_date'))
        batch_op.drop_index(batch_op.f('ix_medication_inventory_item_id'))
        batch_op.drop_index(batch_op.f('ix_medication_flock_id'))
        batch_op.drop_index(batch_op.f('ix_medication_end_date'))
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('amount_used_qty',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('inventory_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_transaction_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_inventory_transaction_inventory_item_id'))
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('imported_weekly_benchmark', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), nullable=True))

    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), nullable=True))

    with op.batch_alter_table('hatchability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hatchability_setting_date'))
        batch_op.drop_index(batch_op.f('ix_hatchability_hatching_date'))
        batch_op.drop_index(batch_op.f('ix_hatchability_flock_id'))
        batch_op.drop_index(batch_op.f('ix_hatchability_candling_date'))
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('global_standard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_theme', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), nullable=True))

    with op.batch_alter_table('flock_grading', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flock_grading_age_week'))
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('flock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('production_start_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), nullable=True))
        batch_op.alter_column('farm_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('floating_note', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_floating_note_x_value'))
        batch_op.drop_index(batch_op.f('ix_floating_note_flock_id'))
        batch_op.drop_index(batch_op.f('ix_floating_note_created_at'))
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('y_value',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('x_value',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('chart_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('flock_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('feed_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), nullable=True))

    with op.batch_alter_table('farm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), nullable=True))

    with op.batch_alter_table('daily_log_photo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_log_photo_note_id'))
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feed_code_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('feed_female', sa.FLOAT(), server_default=sa.text('(0.0)'), nullable=False))
        batch_op.add_column(sa.Column('feed_male', sa.FLOAT(), server_default=sa.text('(0.0)'), nullable=False))
        batch_op.create_foreign_key(None, 'feed_code', ['feed_code_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_daily_log_feed_code_male_id'))
        batch_op.drop_index(batch_op.f('ix_daily_log_feed_code_female_id'))
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('uniformity_female',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('uniformity_male',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('body_weight_female',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('body_weight_male',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('females_out_flock')
        batch_op.drop_column('females_in_flock')
        batch_op.drop_column('males_out_flock')
        batch_op.drop_column('males_in_flock')

    with op.batch_alter_table('clinical_note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinical_note_log_id'))
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('broiler_flock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), nullable=True))

    with op.batch_alter_table('broiler_daily_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), nullable=True))

    op.create_table('_alembic_tmp_broiler_daily_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('flock_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('day_number', sa.INTEGER(), nullable=False),
    sa.Column('death_count', sa.INTEGER(), nullable=True),
    sa.Column('feed_receive', sa.VARCHAR(length=100), nullable=True),
    sa.Column('feed_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('feed_daily_use_kg', sa.FLOAT(), nullable=True),
    sa.Column('body_weight_g', sa.FLOAT(), nullable=True),
    sa.Column('standard_fcr', sa.FLOAT(), nullable=True),
    sa.Column('medication_vaccine', sa.VARCHAR(length=200), nullable=True),
    sa.Column('remarks', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['flock_id'], ['broiler_flock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
