"""Add in/out flock fields

Revision ID: 8ae5a4cb256d
Revises: 321a423db419
Create Date: 2026-05-02 01:17:46.562799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ae5a4cb256d'
down_revision = '321a423db419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.create_index(op.f('ix_clinical_note_log_id'), 'clinical_note', ['log_id'], unique=False)
    except Exception:
        pass

    # op.batch_alter_table bypassed for daily_log to prevent SQLite CircularDependency error
    op.add_column('daily_log', sa.Column('males_in_flock', sa.Integer(), server_default='0', nullable=False))
    op.add_column('daily_log', sa.Column('males_out_flock', sa.Integer(), server_default='0', nullable=False))
    op.add_column('daily_log', sa.Column('females_in_flock', sa.Integer(), server_default='0', nullable=False))
    op.add_column('daily_log', sa.Column('females_out_flock', sa.Integer(), server_default='0', nullable=False))
    # SQLite does not support ALTER COLUMN natively without recreate.
    try:
        op.create_index(op.f('ix_daily_log_feed_code_female_id'), 'daily_log', ['feed_code_female_id'], unique=False)
    except Exception:
        pass
    try:
        op.create_index(op.f('ix_daily_log_feed_code_male_id'), 'daily_log', ['feed_code_male_id'], unique=False)
    except Exception:
        pass

    try:
        op.create_index(op.f('ix_daily_log_photo_note_id'), 'daily_log_photo', ['note_id'], unique=False)
    except Exception:
        pass

    try:
        op.create_index(op.f('ix_floating_note_created_at'), 'floating_note', ['created_at'], unique=False)
    except Exception:
        pass
    try:
        op.create_index(op.f('ix_floating_note_flock_id'), 'floating_note', ['flock_id'], unique=False)
    except Exception:
        pass
    try:
        op.create_index(op.f('ix_floating_note_x_value'), 'floating_note', ['x_value'], unique=False)
    except Exception:
        pass
    op.create_foreign_key(None, 'floating_note', 'flock', ['flock_id'], ['id'])


    try:
        op.create_index(op.f('ix_flock_grading_age_week'), 'flock_grading', ['age_week'], unique=False)
    except Exception:
        pass

    try:
        op.create_index(op.f('ix_hatchability_candling_date'), 'hatchability', ['candling_date'], unique=False)
    except Exception:
        pass
    try:
        op.create_index(op.f('ix_hatchability_flock_id'), 'hatchability', ['flock_id'], unique=False)
    except Exception:
        pass
    try:
        op.create_index(op.f('ix_hatchability_hatching_date'), 'hatchability', ['hatching_date'], unique=False)
    except Exception:
        pass
    try:
        op.create_index(op.f('ix_hatchability_setting_date'), 'hatchability', ['setting_date'], unique=False)
    except Exception:
        pass


    try:
        op.create_index(op.f('ix_inventory_transaction_inventory_item_id'), 'inventory_transaction', ['inventory_item_id'], unique=False)
    except Exception:
        pass
    try:
        op.create_index(op.f('ix_inventory_transaction_transaction_date'), 'inventory_transaction', ['transaction_date'], unique=False)
    except Exception:
        pass

    try:
        op.create_index(op.f('ix_medication_end_date'), 'medication', ['end_date'], unique=False)
    except Exception:
        pass
    try:
        op.create_index(op.f('ix_medication_flock_id'), 'medication', ['flock_id'], unique=False)
    except Exception:
        pass
    try:
        op.create_index(op.f('ix_medication_inventory_item_id'), 'medication', ['inventory_item_id'], unique=False)
    except Exception:
        pass
    try:
        op.create_index(op.f('ix_medication_start_date'), 'medication', ['start_date'], unique=False)
    except Exception:
        pass

    try:
        op.create_index(op.f('ix_partition_weight_log_id'), 'partition_weight', ['log_id'], unique=False)
    except Exception:
        pass

    try:
        op.create_index(op.f('ix_sampling_event_age_week'), 'sampling_event', ['age_week'], unique=False)
    except Exception:
        pass
    try:
        op.create_index(op.f('ix_sampling_event_flock_id'), 'sampling_event', ['flock_id'], unique=False)
    except Exception:
        pass
    try:
        op.create_index(op.f('ix_sampling_event_status'), 'sampling_event', ['status'], unique=False)
    except Exception:
        pass


    try:
        op.create_index(op.f('ix_user_activity_log_timestamp'), 'user_activity_log', ['timestamp'], unique=False)
    except Exception:
        pass
    try:
        op.create_index(op.f('ix_user_activity_log_user_id'), 'user_activity_log', ['user_id'], unique=False)
    except Exception:
        pass
    op.create_foreign_key(None, 'user_activity_log', 'user', ['user_id'], ['id'])

    try:
        op.create_index(op.f('ix_vaccine_actual_date'), 'vaccine', ['actual_date'], unique=False)
    except Exception:
        pass
    try:
        op.create_index(op.f('ix_vaccine_est_date'), 'vaccine', ['est_date'], unique=False)
    except Exception:
        pass
    try:
        op.create_index(op.f('ix_vaccine_flock_id'), 'vaccine', ['flock_id'], unique=False)
    except Exception:
        pass
    try:
        op.create_index(op.f('ix_vaccine_inventory_item_id'), 'vaccine', ['inventory_item_id'], unique=False)
    except Exception:
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_index(op.f('ix_vaccine_inventory_item_id'), table_name='vaccine')
    except Exception:
        pass
    try:
        op.drop_index(op.f('ix_vaccine_flock_id'), table_name='vaccine')
    except Exception:
        pass
    try:
        op.drop_index(op.f('ix_vaccine_est_date'), table_name='vaccine')
    except Exception:
        pass
    try:
        op.drop_index(op.f('ix_vaccine_actual_date'), table_name='vaccine')
    except Exception:
        pass

    try:
        op.drop_index(op.f('ix_user_activity_log_user_id'), table_name='user_activity_log')
    except Exception:
        pass
    try:
        op.drop_index(op.f('ix_user_activity_log_timestamp'), table_name='user_activity_log')
    except Exception:
        pass


    try:
        op.drop_index(op.f('ix_sampling_event_status'), table_name='sampling_event')
    except Exception:
        pass
    try:
        op.drop_index(op.f('ix_sampling_event_flock_id'), table_name='sampling_event')
    except Exception:
        pass
    try:
        op.drop_index(op.f('ix_sampling_event_age_week'), table_name='sampling_event')
    except Exception:
        pass

    try:
        op.drop_index(op.f('ix_partition_weight_log_id'), table_name='partition_weight')
    except Exception:
        pass

    try:
        op.drop_index(op.f('ix_medication_start_date'), table_name='medication')
    except Exception:
        pass
    try:
        op.drop_index(op.f('ix_medication_inventory_item_id'), table_name='medication')
    except Exception:
        pass
    try:
        op.drop_index(op.f('ix_medication_flock_id'), table_name='medication')
    except Exception:
        pass
    try:
        op.drop_index(op.f('ix_medication_end_date'), table_name='medication')
    except Exception:
        pass

    try:
        op.drop_index(op.f('ix_inventory_transaction_transaction_date'), table_name='inventory_transaction')
    except Exception:
        pass
    try:
        op.drop_index(op.f('ix_inventory_transaction_inventory_item_id'), table_name='inventory_transaction')
    except Exception:
        pass


    try:
        op.drop_index(op.f('ix_hatchability_setting_date'), table_name='hatchability')
    except Exception:
        pass
    try:
        op.drop_index(op.f('ix_hatchability_hatching_date'), table_name='hatchability')
    except Exception:
        pass
    try:
        op.drop_index(op.f('ix_hatchability_flock_id'), table_name='hatchability')
    except Exception:
        pass
    try:
        op.drop_index(op.f('ix_hatchability_candling_date'), table_name='hatchability')
    except Exception:
        pass

    try:
        op.drop_index(op.f('ix_flock_grading_age_week'), table_name='flock_grading')
    except Exception:
        pass


    try:
        op.drop_index(op.f('ix_floating_note_x_value'), table_name='floating_note')
    except Exception:
        pass
    try:
        op.drop_index(op.f('ix_floating_note_flock_id'), table_name='floating_note')
    except Exception:
        pass
    try:
        op.drop_index(op.f('ix_floating_note_created_at'), table_name='floating_note')
    except Exception:
        pass

    try:
        op.drop_index(op.f('ix_daily_log_photo_note_id'), table_name='daily_log_photo')
    except Exception:
        pass

    try:
        op.drop_index(op.f('ix_daily_log_feed_code_male_id'), table_name='daily_log')
    except Exception:
        pass
    try:
        op.drop_index(op.f('ix_daily_log_feed_code_female_id'), table_name='daily_log')
    except Exception:
        pass
    try:
        op.drop_index(op.f('ix_daily_log_feed_code_male_id'), table_name='daily_log')
    except Exception:
        pass
    try:
        op.drop_index(op.f('ix_daily_log_feed_code_female_id'), table_name='daily_log')
    except Exception:
        pass
    # Let SQLite handle drops if possible, otherwise skip or pass.
    # SQLite 3.35+ supports DROP COLUMN.
    try:
        op.drop_column('daily_log', 'females_out_flock')
        op.drop_column('daily_log', 'females_in_flock')
        op.drop_column('daily_log', 'males_out_flock')
        op.drop_column('daily_log', 'males_in_flock')
    except Exception as e:
        print("Skipping column drops due to sqlite limitations:", e)

    try:
        op.drop_index(op.f('ix_clinical_note_log_id'), table_name='clinical_note')
    except Exception:
        pass

    # ### end Alembic commands ###
