"""Merge production tracking updates

Revision ID: 8f77f526533c
Revises: e686a2573333
Create Date: 2026-02-12 08:12:35.118773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f77f526533c'
down_revision = 'e686a2573333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mortality_female_hosp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('culls_female_hosp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('females_moved_to_prod', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('females_moved_to_hosp', sa.Integer(), nullable=True))

    with op.batch_alter_table('flock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prod_start_male', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('prod_start_female', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('prod_start_male_hosp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('prod_start_female_hosp', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flock', schema=None) as batch_op:
        batch_op.drop_column('prod_start_female_hosp')
        batch_op.drop_column('prod_start_male_hosp')
        batch_op.drop_column('prod_start_female')
        batch_op.drop_column('prod_start_male')

    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        batch_op.drop_column('females_moved_to_hosp')
        batch_op.drop_column('females_moved_to_prod')
        batch_op.drop_column('culls_female_hosp')
        batch_op.drop_column('mortality_female_hosp')

    # ### end Alembic commands ###
