"""remove photo_path from daily_log

Revision ID: 9782a065a3d5
Revises: 842943bd20a2
Create Date: 2026-02-25 05:40:23.557749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9782a065a3d5'
down_revision = '842943bd20a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        batch_op.drop_column('photo_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_path', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
