"""Add start stock columns to DailyLog

Revision ID: a035faca5735
Revises: 103e6b03e284
Create Date: 2026-03-11 01:27:35.856905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a035faca5735'
down_revision = '103e6b03e284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('males_at_start', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('females_at_start', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        batch_op.drop_column('females_at_start')
        batch_op.drop_column('males_at_start')

    # ### end Alembic commands ###
