"""Set production start counts not null default 0

Revision ID: a7d9b437cae8
Revises: 8f77f526533c
Create Date: 2026-02-14 00:49:58.895742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7d9b437cae8'
down_revision = '8f77f526533c'
branch_labels = None
depends_on = None


def upgrade():
    # Update existing NULLs to 0
    op.execute("UPDATE flock SET prod_start_male = 0 WHERE prod_start_male IS NULL")
    op.execute("UPDATE flock SET prod_start_female = 0 WHERE prod_start_female IS NULL")
    op.execute("UPDATE flock SET prod_start_male_hosp = 0 WHERE prod_start_male_hosp IS NULL")
    op.execute("UPDATE flock SET prod_start_female_hosp = 0 WHERE prod_start_female_hosp IS NULL")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flock', schema=None) as batch_op:
        batch_op.alter_column('prod_start_male',
               existing_type=sa.INTEGER(),
               nullable=False,
               server_default='0')
        batch_op.alter_column('prod_start_female',
               existing_type=sa.INTEGER(),
               nullable=False,
               server_default='0')
        batch_op.alter_column('prod_start_male_hosp',
               existing_type=sa.INTEGER(),
               nullable=False,
               server_default='0')
        batch_op.alter_column('prod_start_female_hosp',
               existing_type=sa.INTEGER(),
               nullable=False,
               server_default='0')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flock', schema=None) as batch_op:
        batch_op.alter_column('prod_start_female_hosp',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('prod_start_male_hosp',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('prod_start_female',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('prod_start_male',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
