"""Add Login Required to Global Standard

Revision ID: b7d8c9a0e1f2
Revises: 982f1b4c92d5
Create Date: 2026-02-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'b7d8c9a0e1f2'
down_revision = '982f1b4c92d5'
branch_labels = None
depends_on = None


def upgrade():
    # Check if column exists to handle cases where fix_migration_conflict.py ran
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('global_standard')]

    if 'login_required' not in columns:
        # ### commands auto generated by Alembic - please adjust! ###
        with op.batch_alter_table('global_standard', schema=None) as batch_op:
            batch_op.add_column(sa.Column('login_required', sa.Boolean(), nullable=True))

        # Set default value for existing rows
        # SQLite uses 1 for True
        op.execute("UPDATE global_standard SET login_required = 1 WHERE login_required IS NULL")
        # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('global_standard')]

    if 'login_required' in columns:
        with op.batch_alter_table('global_standard', schema=None) as batch_op:
            batch_op.drop_column('login_required')

    # ### end Alembic commands ###
