"""Remove start of lay date

Revision ID: c5517872a7f7
Revises: 33de47d14183
Create Date: 2026-05-03 03:18:14.003806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5517872a7f7'
down_revision = '33de47d14183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broiler_flock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_name', sa.String(length=100), nullable=True),
    sa.Column('house_name', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('breed', sa.String(length=50), nullable=True),
    sa.Column('intake_birds', sa.Integer(), nullable=False),
    sa.Column('intake_date', sa.Date(), nullable=False),
    sa.Column('arrival_weight_g', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broiler_flock'))
    )
    op.create_table('notification_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('metric', sa.String(length=50), nullable=False),
    sa.Column('operator', sa.String(length=10), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_rule'))
    )
    op.create_table('broiler_daily_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('death_count', sa.Integer(), nullable=True),
    sa.Column('feed_receive', sa.String(length=100), nullable=True),
    sa.Column('feed_type', sa.String(length=100), nullable=True),
    sa.Column('feed_daily_use_kg', sa.Float(), nullable=True),
    sa.Column('body_weight_g', sa.Float(), nullable=True),
    sa.Column('standard_fcr', sa.Float(), nullable=True),
    sa.Column('medication_vaccine', sa.String(length=200), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['flock_id'], ['broiler_flock.id'], name=op.f('fk_broiler_daily_log_flock_id_broiler_flock')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broiler_daily_log'))
    )
    with op.batch_alter_table('broiler_daily_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_broiler_daily_log_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_broiler_daily_log_flock_id'), ['flock_id'], unique=False)

    op.create_table('flock_grading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('age_week', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('average_weight', sa.Float(), nullable=True),
    sa.Column('uniformity', sa.Float(), nullable=True),
    sa.Column('lowest_weight', sa.Float(), nullable=True),
    sa.Column('highest_weight', sa.Float(), nullable=True),
    sa.Column('grading_bins', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], name=op.f('fk_flock_grading_house_id_house')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flock_grading'))
    )
    with op.batch_alter_table('flock_grading', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flock_grading_age_week'), ['age_week'], unique=False)
        batch_op.create_index(batch_op.f('ix_flock_grading_house_id'), ['house_id'], unique=False)

    op.create_table('notification_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_notification_history_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_history'))
    )
    with op.batch_alter_table('notification_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_history_user_id'), ['user_id'], unique=False)

    op.create_table('push_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_push_subscription_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_subscription'))
    )
    with op.batch_alter_table('push_subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_subscription_user_id'), ['user_id'], unique=False)

    op.create_table('user_activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_activity_log_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_activity_log'))
    )
    with op.batch_alter_table('user_activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_activity_log_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_activity_log_user_id'), ['user_id'], unique=False)

    op.create_table('studio_annotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flock_id', sa.Integer(), nullable=False),
    sa.Column('chart_identifier', sa.String(length=50), nullable=False),
    sa.Column('anchor_data_x', sa.String(length=50), nullable=False),
    sa.Column('anchor_data_y', sa.Float(), nullable=False),
    sa.Column('fabric_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flock_id'], ['flock.id'], name=op.f('fk_studio_annotation_flock_id_flock')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_studio_annotation'))
    )
    with op.batch_alter_table('studio_annotation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studio_annotation_chart_identifier'), ['chart_identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_studio_annotation_flock_id'), ['flock_id'], unique=False)

    op.drop_table('floating_note')
    op.drop_table('overview_configuration')
    op.drop_table('chart_configuration')
    with op.batch_alter_table('clinical_note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_index(batch_op.f('ix_clinical_note_log_id'), ['log_id'], unique=False)

    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('males_in_flock', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('males_out_flock', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('females_in_flock', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('females_out_flock', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('is_daily_entry_submitted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('remarks', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('selection_done', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('spiking', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), server_default='1', nullable=False))
        batch_op.alter_column('body_weight_male',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('body_weight_female',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('uniformity_male',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('uniformity_female',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_daily_log_feed_code_female_id'), ['feed_code_female_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_log_feed_code_male_id'), ['feed_code_male_id'], unique=False)
        batch_op.drop_column('feed_male')
        batch_op.drop_column('feed_female')

    with op.batch_alter_table('daily_log_photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_index(batch_op.f('ix_daily_log_photo_note_id'), ['note_id'], unique=False)

    with op.batch_alter_table('flock', schema=None) as batch_op:
        batch_op.alter_column('farm_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_flock_batch_id'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_flock_flock_id'), ['flock_id'])
        batch_op.drop_column('start_of_lay_date')
        batch_op.drop_column('production_start_date')

    with op.batch_alter_table('hatchability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_index(batch_op.f('ix_hatchability_candling_date'), ['candling_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_hatchability_flock_id'), ['flock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hatchability_hatching_date'), ['hatching_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_hatchability_setting_date'), ['setting_date'], unique=False)

    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('unit_of_measurement', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), server_default='1', nullable=False))

    with op.batch_alter_table('inventory_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('classification', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_index(batch_op.f('ix_inventory_transaction_inventory_item_id'), ['inventory_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transaction_transaction_date'), ['transaction_date'], unique=False)

    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_index(batch_op.f('ix_medication_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_flock_id'), ['flock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_inventory_item_id'), ['inventory_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_start_date'), ['start_date'], unique=False)

    with op.batch_alter_table('partition_weight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_index(batch_op.f('ix_partition_weight_log_id'), ['log_id'], unique=False)

    with op.batch_alter_table('sampling_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_index(batch_op.f('ix_sampling_event_age_week'), ['age_week'], unique=False)
        batch_op.create_index(batch_op.f('ix_sampling_event_flock_id'), ['flock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sampling_event_status'), ['status'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farm_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))

    with op.batch_alter_table('vaccine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_index(batch_op.f('ix_vaccine_actual_date'), ['actual_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_vaccine_est_date'), ['est_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_vaccine_flock_id'), ['flock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vaccine_inventory_item_id'), ['inventory_item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaccine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vaccine_inventory_item_id'))
        batch_op.drop_index(batch_op.f('ix_vaccine_flock_id'))
        batch_op.drop_index(batch_op.f('ix_vaccine_est_date'))
        batch_op.drop_index(batch_op.f('ix_vaccine_actual_date'))
        batch_op.drop_column('version')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')
        batch_op.drop_column('farm_id')

    with op.batch_alter_table('sampling_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sampling_event_status'))
        batch_op.drop_index(batch_op.f('ix_sampling_event_flock_id'))
        batch_op.drop_index(batch_op.f('ix_sampling_event_age_week'))
        batch_op.drop_column('version')

    with op.batch_alter_table('partition_weight', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partition_weight_log_id'))
        batch_op.drop_column('version')

    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medication_start_date'))
        batch_op.drop_index(batch_op.f('ix_medication_inventory_item_id'))
        batch_op.drop_index(batch_op.f('ix_medication_flock_id'))
        batch_op.drop_index(batch_op.f('ix_medication_end_date'))
        batch_op.drop_column('version')

    with op.batch_alter_table('inventory_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_transaction_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_inventory_transaction_inventory_item_id'))
        batch_op.drop_column('version')
        batch_op.drop_column('classification')
        batch_op.drop_column('location')

    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_column('version')
        batch_op.drop_column('location')
        batch_op.drop_column('unit_of_measurement')
        batch_op.drop_column('category')

    with op.batch_alter_table('hatchability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hatchability_setting_date'))
        batch_op.drop_index(batch_op.f('ix_hatchability_hatching_date'))
        batch_op.drop_index(batch_op.f('ix_hatchability_flock_id'))
        batch_op.drop_index(batch_op.f('ix_hatchability_candling_date'))
        batch_op.drop_column('version')

    with op.batch_alter_table('flock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('production_start_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('start_of_lay_date', sa.DATE(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_flock_flock_id'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_flock_batch_id'), ['flock_id'])
        batch_op.alter_column('farm_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('daily_log_photo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_log_photo_note_id'))
        batch_op.drop_column('version')

    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feed_female', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('feed_male', sa.FLOAT(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_daily_log_feed_code_male_id'))
        batch_op.drop_index(batch_op.f('ix_daily_log_feed_code_female_id'))
        batch_op.alter_column('uniformity_female',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('uniformity_male',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('body_weight_female',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('body_weight_male',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('version')
        batch_op.drop_column('spiking')
        batch_op.drop_column('selection_done')
        batch_op.drop_column('remarks')
        batch_op.drop_column('is_daily_entry_submitted')
        batch_op.drop_column('females_out_flock')
        batch_op.drop_column('females_in_flock')
        batch_op.drop_column('males_out_flock')
        batch_op.drop_column('males_in_flock')

    with op.batch_alter_table('clinical_note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinical_note_log_id'))
        batch_op.drop_column('version')

    op.create_table('chart_configuration',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('house_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('chart_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('config_json', sa.TEXT(), nullable=False),
    sa.Column('is_template', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], name=op.f('fk_chart_configuration_house_id_house')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chart_configuration'))
    )
    op.create_table('overview_configuration',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('house_id', sa.INTEGER(), nullable=False),
    sa.Column('visible_metrics_json', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], name=op.f('fk_overview_configuration_house_id_house')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_overview_configuration')),
    sa.UniqueConstraint('house_id', name=op.f('uq_overview_configuration_house_id'))
    )
    op.create_table('floating_note',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('flock_id', sa.INTEGER(), nullable=False),
    sa.Column('chart_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('x_value', sa.VARCHAR(length=50), nullable=False),
    sa.Column('y_value', sa.FLOAT(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['flock_id'], ['flock.id'], name=op.f('fk_floating_note_flock_id_flock')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_floating_note'))
    )
    with op.batch_alter_table('studio_annotation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_studio_annotation_flock_id'))
        batch_op.drop_index(batch_op.f('ix_studio_annotation_chart_identifier'))

    op.drop_table('studio_annotation')
    with op.batch_alter_table('user_activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_activity_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_activity_log_timestamp'))

    op.drop_table('user_activity_log')
    with op.batch_alter_table('push_subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscription_user_id'))

    op.drop_table('push_subscription')
    with op.batch_alter_table('notification_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_history_created_at'))

    op.drop_table('notification_history')
    with op.batch_alter_table('flock_grading', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flock_grading_house_id'))
        batch_op.drop_index(batch_op.f('ix_flock_grading_age_week'))

    op.drop_table('flock_grading')
    with op.batch_alter_table('broiler_daily_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_broiler_daily_log_flock_id'))
        batch_op.drop_index(batch_op.f('ix_broiler_daily_log_date'))

    op.drop_table('broiler_daily_log')
    op.drop_table('notification_rule')
    op.drop_table('broiler_flock')
    # ### end Alembic commands ###
