"""Drop FloatingNote table

Revision ID: drop_floating_note_table
Revises: 9f7544d4f807
Create Date: 2024-05-18 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'drop_floating_note_table'
down_revision = '9f7544d4f807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_floating_note_created_at', table_name='floating_note')
    op.drop_index('ix_floating_note_flock_id', table_name='floating_note')
    op.drop_index('ix_floating_note_x_value', table_name='floating_note')
    op.drop_table('floating_note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('floating_note',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('flock_id', sa.INTEGER(), nullable=False),
    sa.Column('chart_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('x_value', sa.VARCHAR(length=50), nullable=False),
    sa.Column('y_value', sa.FLOAT(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['flock_id'], ['flock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_floating_note_x_value', 'floating_note', ['x_value'], unique=False)
    op.create_index('ix_floating_note_flock_id', 'floating_note', ['flock_id'], unique=False)
    op.create_index('ix_floating_note_created_at', 'floating_note', ['created_at'], unique=False)
    # ### end Alembic commands ###
