"""Add GlobalStandard

Revision ID: e686a2573333
Revises: 4ea3b6f0007c
Create Date: 2026-02-12 06:45:47.267723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e686a2573333'
down_revision = '4ea3b6f0007c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_standard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('std_mortality_daily', sa.Float(), nullable=True),
    sa.Column('std_mortality_weekly', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('global_standard')
    # ### end Alembic commands ###
