"""Add indexes

Revision ID: ecafcdfc06fc
Revises: 1a2b3c4d5e6f
Create Date: 2026-02-23 13:22:59.067149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecafcdfc06fc'
down_revision = '1a2b3c4d5e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_log_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_log_flock_id'), ['flock_id'], unique=False)

    with op.batch_alter_table('flock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flock_house_id'), ['house_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flock_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flock_status'))
        batch_op.drop_index(batch_op.f('ix_flock_house_id'))

    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_log_flock_id'))
        batch_op.drop_index(batch_op.f('ix_daily_log_date'))

    # ### end Alembic commands ###
