"""Add Farm model and link to Flock

Revision ID: fe4643e18171
Revises: 227589a3a171
Create Date: 2026-03-02 14:00:19.267749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe4643e18171'
down_revision = '227589a3a171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('flock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farm_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_flock_farm_id'), ['farm_id'], unique=False)
        batch_op.create_foreign_key('fk_flock_farm_id', 'farm', ['farm_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flock', schema=None) as batch_op:
        batch_op.drop_constraint('fk_flock_farm_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_flock_farm_id'))
        batch_op.drop_column('farm_id')

    op.create_table('weekly_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('flock_id', sa.INTEGER(), nullable=False),
    sa.Column('week', sa.INTEGER(), nullable=False),
    sa.Column('mortality_male', sa.INTEGER(), nullable=True),
    sa.Column('mortality_female', sa.INTEGER(), nullable=True),
    sa.Column('culls_male', sa.INTEGER(), nullable=True),
    sa.Column('culls_female', sa.INTEGER(), nullable=True),
    sa.Column('eggs_collected', sa.INTEGER(), nullable=True),
    sa.Column('bw_male', sa.INTEGER(), nullable=True),
    sa.Column('bw_female', sa.INTEGER(), nullable=True),
    sa.Column('feed_male', sa.FLOAT(), nullable=True),
    sa.Column('feed_female', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['flock_id'], ['flock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('farm')
    # ### end Alembic commands ###
